// @flow
'use strict';
var exampleVfrCharts = [
  {
    regionName: 'Favorite 1 super long long long name test gonna add so much more now to see some extra shitssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: true,
    uniqueId: 0,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 1,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 2,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 3,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 4,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 5,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 6,
  },
  {
    regionName: 'Favorite 2',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: true,
    uniqueId: 7,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 8,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 9,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 10,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 11,
  },
  {
    regionName: 'Favorite 3',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: true,
    uniqueId: 12,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 13,
  },
  {
    regionName: 'Seattle  fav test',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 14,
  },
  {
    regionName: 'Seattle',
    regionId: 'SEA',
    publicationDate: '2016-01-29',
    expirationDate: '2016-12-05',
    revisionNumber: 0,
    chartUrl: 'https://www.google.com',
    filePath: '',
    isFavorited: false,
    uniqueId: 15,
  }
];
const getSavedCharts = () => {
  // this is where we will load our charts from disk, for now populate with this list
  return exampleVfrCharts;
}
export { getSavedCharts};
