// @flow
'use strict';

const getSavedCharts = () => {
  // this is where we will load our charts from disk, for now populate with this list
  var exampleVfrCharts = [
    {
      regionName: ' Favorite 1',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: true,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Favorite 2',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: true,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Favorite 3',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: true,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    },
    {
      regionName: ' Seattle',
      regionId: 'SEA',
      publicationDate: '2016-01-29',
      expirationDate: '2016-12-05',
      revisionNumber: 0,
      chartUrl: 'https://www.google.com',
      filePath: '',
      isFavorited: false,
    }
  ];
  
  return exampleVfrCharts;
}

export { getSavedCharts };
